### ISSUE TITLE
Pushing Tags doesn't seem to trigger an update

### ISSUE THREAD

**Issue by phillord** [milkypostman/melpa#2727] opened 2015-05-01 16:41 UTC
A bit hard for me to test, but it seems to me that melpa only updates on a commit, and not on a new tag.

I generally commit my new releases, wait for travis to build and then push the tag afterwards. But, then I need MELPA to rebuild WITH the tag, or melpa stable doesn't update. This seems to not be happening.

**Comment by purcell** [comment] 2015-05-02 16:32
Hi Phil -- please can you indicate a specific package for which this doesn't appear to be working, so I can look at what's happening on the server?

**Comment by phillord** [comment] 2015-05-04 08:13
It seems to have happened several times for m-buffer and lentic. It's possible I am wrong. I will try and test it properly at the next release -- but it's hard to debug because I don't want to push junk tags!

**Comment by purcell** [comment] 2015-05-04 15:06
Yeah, I'd really like to fix this if there is a problem.

MELPA and MELPA Stable are completely separate servers, so the former doesn't affect the latter. It doesn't look like the code requires a new commit in order for a new stable package to build -- we just run `git remote update`, look for the highest-numbered tag and then build it unconditionally.

I could set up an artificial test, but if you don't mind I'd rather not get pulled into that just yet. When you notice something awry, ping me and I'll take a look in short order. Hope that's okay.

**Comment by milkypostman** [comment] 2015-05-04 16:01
but it seems that it does automatically update eventually?

**Comment by purcell** [comment] 2015-05-04 16:17
Perhaps only in response to new commits.

**Comment by phillord** [comment] 2015-05-05 13:11
Steve Purcell <notifications@github.com> writes:

> Yeah, I'd really like to fix this if there is a problem.
>
> MELPA and MELPA Stable are completely separate servers, so the former doesn't
> affect the latter.

Ah!

So the twitter feed on the front page of melpa stable (which is the same
as the one on melpa) is not actually about melpa stable -- obvious in
hindsight I guess.

This may well be the issue -- I am probably just being impatient. I need
to poll for stable releases I guess.


> It doesn't look like the code requires a new commit in
> order for a new stable package to build -- we just run `git remote update`,
> look for the highest-numbered tag and then build it unconditionally.
>
> I could set up an artificial test, but if you don't mind I'd rather
> not get pulled into that just yet. When you notice something awry, ping
> me and I'll take a look in short order. Hope that's okay.


Sounds sensible. Next time I do a release, I will leave it for a long
time, and see whether it works, and close this issue then.

Phil

**Comment by purcell** [comment] 2015-07-20 06:33
@phillord Do you know if this is still a problem for you?

**Comment by mdorman** [comment] 2015-09-03 13:54
@purcell Since I've been going around asking people to tag releases over the last few days (thanks for doing haskell-snippets!), I've got an example, I think.  NicolasPetton/pass was tagged 1.0 earlier today, and though the package is available on melpa, it's not showing up on melpa-stable.

**Comment by purcell** [comment] 2015-09-04 07:26
I believe I've identified and fixed the cause of this. We'll know for sure in an hour or two, but I'm confident enough that I'm going to go ahead and close this now. :-)

**Closed by purcell** 2015-09-04 07:26 UTC

**Comment by mdorman** [comment] 2015-09-04 10:17
Awesome!
